### ISSUE TITLE
When I load the .fbx model this happens.

### ISSUE THREAD

**Issue by X-DE1** [Zarbuz/FileToVox#70] opened 2022-12-08 05:09 UTC
When I load this .fbx models apps with no texture.
here are the models
https://www.models-resource.com/pc_computer/killingfloor2/model/40454/
https://www.models-resource.com/pc_computer/killingfloor2/model/40455/
![imagen](https://user-images.githubusercontent.com/101435795/206361568-1468ea42-8317-401b-8e0e-0eb4409ad58b.png)
![imagen](https://user-images.githubusercontent.com/101435795/206361612-5890688f-8aea-4392-948f-5b23d4f37887.png)
Edit: I tried the models in Mesh to Vox 2.9 and the same thing happens

**Comment by Zarbuz** [comment] 2023-04-17 18:31
Hello sorry for this late answer.
I tried to open the FBX file and it seems that the reference to the texture are incorrect. I tried to open it with another software (Blender) and textures are missing.
I close this issue since it's not a bug related to MeshTovox

**Closed by Zarbuz** 2023-04-17 18:31 UTC
