### ISSUE TITLE
Bad voxel generation in MeshSampler

### ISSUE THREAD

**Issue by Daedalusia** [Zarbuz/FileToVox#48] opened 2022-01-17 01:18 UTC
The voxels generated in MeshSampler look terrible compared to the ones you get when you just drag an .obj into MagicaVoxel, but MagicaVoxel doesn't read .mtl textures so you can't really do anything with it. If you could match the algorithm for MeshSampler to the current one of MagicaVoxel, that would be awesome.

**Comment by Zarbuz** [comment] 2022-01-17 08:17
Saying that the results are bad without giving an example file is useless, I have excellent results with the 3D models that I use so to determine the cause of the problem without a source file I will not go far

**Comment by Starkemis** [comment] 2022-01-17 10:57
Oh, right my bad. I should have left a model.

Please compare
between MeshSampler & drag and drop into MagicaVoxel

[WatchForZarbuz.zip](https://github.com/Zarbuz/FileToVox/files/7881256/WatchForZarbuz.zip)

I'm on a 3090, model type is polygonal of course. I'm using the standard 128 for both MeshSampler and MagicaVoxel.

**Comment by Zarbuz** [comment] 2022-06-21 16:45
Fixed in MeshToVox v2.6

**Closed by Zarbuz** 2022-06-21 16:45 UTC
