### ISSUE TITLE
textures are gonna be broken after voxelization process in mesh sampler 

### ISSUE THREAD

**Issue by alieskan** [Zarbuz/FileToVox#49] opened 2022-01-17 12:04 UTC
hi , i have problem with mesh sampler , when I try to voxelization obj or fbx file with mesh sampler , after process textures are broken and blending to each other 
![image](https://user-images.githubusercontent.com/89135659/149766332-74968dfe-45ef-4870-a7d1-a618fbbda796.png)
![image](https://user-images.githubusercontent.com/89135659/149766486-658522bd-e427-477f-8a21-a6672bc0a709.png)

**Comment by Zarbuz** [comment] 2022-02-02 21:25
Do you know if the sum of the size of all textures exceed 4096x4096px ? I can probably add an option to set the maximal size of the atlas after the baking to avoid this bug

**Comment by svensec** [comment] 2022-02-04 08:37
Hi Zarbuz, I also have this kind of bug after voxelization process from .fbx file format. As you stated above, yes the texture is 4096x4096px. Is there a problem if I used a texture around that size? I'll attach the picture below for your reference.


![before](https://user-images.githubusercontent.com/57976501/152497467-51a56c73-24a0-4be4-8ca6-baac3cb7b668.PNG)
![after](https://user-images.githubusercontent.com/57976501/152497483-2a7c2f8e-5db4-4dcc-b568-24fd62b085e7.PNG)

**Comment by svensec** [comment] 2022-02-07 09:43
update: I've been scaling from 4096x4096 to 1024x1024, nothing works. The problem is still happening.

**Comment by Zarbuz** [comment] 2022-02-10 18:02
Hello, can you provide the 3D model please ?

**Comment by Zarbuz** [comment] 2022-03-12 09:51
Should be fixed in v2.4

**Closed by Zarbuz** 2022-03-12 09:51 UTC
